"""
Generate the MuJoCo MJCF model for the IEE Hexapod.

All dimensions are PLACEHOLDERS for a ~20 in (510 mm) tip-to-tip hexapod
until the leg CAD is finished. Edit the PARAMETERS block and re-run:

    python sim/models/build_hexapod.py

Units: meters, kilograms, radians, newton-meters.

Joint conventions (every leg):
    coxa  - yaw about vertical axis, + is counter-clockwise seen from above
              (left legs swing rearward, right legs swing forward)
    femur - pitch, + lifts the knee UP
    tibia - pitch, + swings the foot OUTWARD
    All joints at 0  ->  femur horizontal, tibia vertical (standing pose).
"""
import math
from pathlib import Path

# ============================ PARAMETERS ============================
# --- Geometry (placeholders; replace with CAD numbers) ---
MOUNT_RADIUS = 0.100      # body center -> coxa joint, horizontal
COXA_LEN     = 0.055      # coxa joint -> femur joint
FEMUR_LEN    = 0.100      # femur joint -> tibia joint
TIBIA_LEN    = 0.140      # tibia joint -> foot center
FOOT_RADIUS  = 0.012      # rubber foot tip
BODY_HALF    = (0.110, 0.080, 0.020)   # body box half-sizes (x, y, z)

# Leg mount angles, degrees from +x (forward), counter-clockwise
LEGS = {
    "LF":  45.0, "LM":  90.0, "LR":  135.0,
    "RF": -45.0, "RM": -90.0, "RR": -135.0,
}

# --- Mass (estimates) ---
# Body includes: plate/frame, 6 coxa servos, 3S 6000mAh pack, Pi 5 + AI HAT+,
# Teensy, bus adapters, IMU, wiring.
BODY_MASS  = 1.60
COXA_MASS  = 0.075        # femur servo + bracket
FEMUR_MASS = 0.085        # tibia servo + link
TIBIA_MASS = 0.035        # tibia link
FOOT_MASS  = 0.005

# --- Actuator model: Feetech STS3215 (12 V, 30 kg-cm stall) ---
STALL_TORQUE = 2.94       # N*m  (30 kg-cm)
TORQUE_LIMIT = 2.94       # sim cap; randomize downward in training
KP           = 20.0       # position gain, N*m/rad (tune vs. step response)
DAMPING      = 0.15       # N*m*s/rad
ARMATURE     = 0.005      # reflected rotor inertia, kg*m^2
FRICTIONLOSS = 0.03       # N*m

# Joint ranges (rad)
COXA_RANGE  = (-0.80, 0.80)
FEMUR_RANGE = (-1.20, 1.60)
TIBIA_RANGE = (-1.60, 1.20)

# --- Simulation ---
TIMESTEP = 0.004          # 250 Hz physics; policy will act every 5 steps (50 Hz)
FOOT_FRICTION = "1.0 0.02 0.01"
# ====================================================================

OUT = Path(__file__).with_name("hexapod.xml")


def f(x):
    return f"{x:.4f}".rstrip("0").rstrip(".") if x != 0 else "0"


def v(*xs):
    return " ".join(f(x) for x in xs)


def leg_xml(name, deg):
    a = math.radians(deg)
    x, y = MOUNT_RADIUS * math.cos(a), MOUNT_RADIUS * math.sin(a)
    return f"""
    <body name="{name}_coxa" pos="{v(x, y, 0)}" euler="0 0 {f(a)}">
      <joint name="{name}_coxa" class="coxa"/>
      <geom class="link" fromto="{v(0, 0, 0, COXA_LEN, 0, 0)}" mass="{f(COXA_MASS)}"/>
      <body name="{name}_femur" pos="{v(COXA_LEN, 0, 0)}">
        <joint name="{name}_femur" class="femur"/>
        <geom class="link" fromto="{v(0, 0, 0, FEMUR_LEN, 0, 0)}" mass="{f(FEMUR_MASS)}"/>
        <body name="{name}_tibia" pos="{v(FEMUR_LEN, 0, 0)}">
          <joint name="{name}_tibia" class="tibia"/>
          <geom class="link" fromto="{v(0, 0, 0, 0, 0, -TIBIA_LEN)}" mass="{f(TIBIA_MASS)}"/>
          <geom name="{name}_foot" class="foot" pos="{v(0, 0, -TIBIA_LEN)}" mass="{f(FOOT_MASS)}"/>
          <site name="{name}_foot" pos="{v(0, 0, -TIBIA_LEN)}" size="0.005"/>
        </body>
      </body>
    </body>"""


def build():
    stand_z = TIBIA_LEN + FOOT_RADIUS + 0.003
    legs = "".join(leg_xml(n, d) for n, d in LEGS.items())
    acts = "\n".join(
        f'    <position name="{n}_{j}" joint="{n}_{j}" class="{j}"/>'
        for n in LEGS for j in ("coxa", "femur", "tibia")
    )
    nu = 3 * len(LEGS)
    home_qpos = v(0, 0, stand_z, 1, 0, 0, 0) + " " + " ".join(["0"] * nu)
    home_ctrl = " ".join(["0"] * nu)

    def jclass(cls, axis, rng):
        return f"""
    <default class="{cls}">
      <joint axis="{axis}" range="{v(*rng)}"/>
      <position ctrlrange="{v(*rng)}"/>
    </default>"""

    xml = f"""<!-- AUTO-GENERATED by build_hexapod.py. Edit the parameters there, not this file. -->
<mujoco model="iee_hexapod">
  <compiler angle="radian" autolimits="true"/>
  <option timestep="{f(TIMESTEP)}" integrator="implicitfast"/>

  <default>
    <geom contype="0" conaffinity="0" rgba="0.55 0.57 0.6 1"/>
    <joint damping="{f(DAMPING)}" armature="{f(ARMATURE)}" frictionloss="{f(FRICTIONLOSS)}"/>
    <position kp="{f(KP)}" forcerange="{v(-TORQUE_LIMIT, TORQUE_LIMIT)}"/>
    <default class="link">
      <geom type="capsule" size="0.012"/>
    </default>
    <default class="foot">
      <geom type="sphere" size="{f(FOOT_RADIUS)}" contype="1" conaffinity="0"
            friction="{FOOT_FRICTION}" rgba="0.1 0.1 0.1 1"/>
    </default>{jclass("coxa", "0 0 1", COXA_RANGE)}{jclass("femur", "0 -1 0", FEMUR_RANGE)}{jclass("tibia", "0 -1 0", TIBIA_RANGE)}
  </default>

  <asset>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
             width="512" height="512"/>
    <material name="grid" texture="grid" texrepeat="8 8" reflectance="0.1"/>
    <texture type="skybox" builtin="gradient" rgb1="0.4 0.6 0.8" rgb2="0 0 0" width="512" height="512"/>
  </asset>

  <worldbody>
    <light pos="0 0 3" dir="0 0 -1" directional="true"/>
    <geom name="floor" type="plane" size="0 0 0.05" material="grid" contype="1" conaffinity="1"/>

    <body name="torso" pos="{v(0, 0, stand_z)}">
      <freejoint name="root"/>
      <geom name="torso" type="box" size="{v(*BODY_HALF)}" mass="{f(BODY_MASS)}"
            contype="1" conaffinity="0" rgba="0.2 0.35 0.6 1"/>
      <site name="imu" pos="0 0 0" size="0.01"/>
      <camera name="track" mode="trackcom" pos="0 -1.0 0.6" xyaxes="1 0 0 0 0.5 1"/>{legs}
    </body>
  </worldbody>

  <actuator>
{acts}
  </actuator>

  <sensor>
    <gyro name="imu_gyro" site="imu"/>
    <accelerometer name="imu_accel" site="imu"/>
    <framequat name="imu_quat" objtype="site" objname="imu"/>
  </sensor>

  <keyframe>
    <key name="home" qpos="{home_qpos}" ctrl="{home_ctrl}"/>
  </keyframe>
</mujoco>
"""
    OUT.write_text(xml)
    return stand_z


def torque_check():
    """Static femur torque when 3 legs (tripod) carry the whole robot."""
    leg_mass = COXA_MASS + FEMUR_MASS + TIBIA_MASS + FOOT_MASS
    total = BODY_MASS + len(LEGS) * leg_mass
    per_leg_n = total * 9.81 / 3
    for label, reach in (("standing (tibia vertical)", FEMUR_LEN),
                         ("foot swung out 45 deg", FEMUR_LEN + TIBIA_LEN * math.sin(math.radians(45)))):
        t = per_leg_n * reach
        print(f"  femur torque, {label:26s}: {t:.2f} N*m "
              f"({t / 0.0981:.1f} kg-cm, {100 * t / STALL_TORQUE:.0f}% of stall)")
    return total


if __name__ == "__main__":
    stand_z = build()
    span = 2 * (MOUNT_RADIUS + COXA_LEN + FEMUR_LEN)
    print(f"Wrote {OUT}")
    print(f"  tip-to-tip span (mid legs): {span * 1000:.0f} mm ({span / 0.0254:.1f} in)")
    print(f"  standing body height:       {stand_z * 1000:.0f} mm")
    total = torque_check()
    print(f"  estimated total mass:       {total:.2f} kg")
